name: cmf
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0  # تم تحديث الإصدار
  firebase_messaging: ^15.0.1  # تم تحديث الإصدار ونقله إلى dependencies
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  permission_handler: ^12.0.1
  fluttertoast: ^8.2.5  # تم تحديث الإصدار
  http: ^1.2.1  # تم تحديث الإصدار

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0 # تم توحيد الإصدار مع lints
  leak_tracker: ^10.0.9
  leak_tracker_flutter_testing: ^3.0.2
  # leak_tracker_testing: ^3.0.1
#  //lints: ^4.0.0 # تم توحيد الإصدار مع flutter_lints
  vm_service: ^15.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/car_parts_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/car_parts_icon.png
